### ISSUE TITLE
No operator congfig file found

### ISSUE THREAD

**Issue by Andy-Kin3** [smswithoutborders/Deku#2]
I run into this error after installing and checking status
![Screenshot from 2021-06-22 21-01-08](https://user-images.githubusercontent.com/49214978/122992554-268cfe80-d39e-11eb-994e-e19529adf227.png)
Ant suggestions on my issue please, I'll like some help

**Comment by sherlockwisdom** [comment]
Please run this commands:
`
# from the root dir of the project
sudo make remove
cp package/isp_configs/example.operators.ini package/isp_configs/operators.ini
sudo make install
sudo make run
`

**Comment by Andy-Kin3** [comment]
Thank you sir

**Comment by Andy-Kin3** [comment]
Finally sir,
Deku is active and running smoothly. What next should I do to begin using
it?
